# Generated by Django 3.1 on 2020-11-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallBoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=200, null=True)),
                ('is_read', models.IntegerField(default=0)),
                ('info_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50, null=True)),
                ('send_name', models.CharField(max_length=50, null=True)),
                ('aid', models.CharField(max_length=50, null=True)),
                ('receive_name', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('info_datetime', models.DateTimeField(auto_now=True)),
                ('is_read', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('sort_num', models.IntegerField(default=0)),
                ('content', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=200, null=True)),
                ('info_datetime', models.DateTimeField(auto_now=True)),
                ('is_modify', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('info_datetime', models.DateTimeField(auto_now=True)),
                ('is_show', models.IntegerField(default=1, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(null=True)),
                ('module_state', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('content', models.TextField(null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('total_output', models.IntegerField(default=0, null=True)),
                ('total_float', models.IntegerField(default=0, null=True)),
                ('real_output', models.IntegerField(default=0, null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('progress', models.IntegerField(default=0, null=True)),
                ('plan_state', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('station', models.CharField(max_length=20, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('op_flag', models.IntegerField(default=1, null=True)),
                ('info_datetime', models.DateTimeField(auto_now=True)),
                ('is_login', models.IntegerField(default=0, null=True)),
                ('userType', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('content', models.CharField(max_length=500, null=True)),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('w_output', models.IntegerField(null=True)),
                ('productivity', models.FloatField(default=0, null=True)),
                ('w_time', models.FloatField(default=0, null=True)),
                ('timeSpent', models.CharField(max_length=50, null=True)),
                ('p_state', models.IntegerField(default=0, null=True)),
                ('content', models.TextField(null=True)),
                ('job_num', models.CharField(max_length=20, null=True)),
                ('distribute_time', models.DateTimeField(auto_now=True, null=True)),
                ('distribute_print_count', models.IntegerField(default=0)),
                ('finished_time', models.DateTimeField(auto_now=True, null=True)),
                ('finished_print_count', models.IntegerField(default=0)),
                ('modify_count', models.IntegerField(default=2)),
                ('cutMoney', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('op_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo')),
                ('p_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.process_name')),
                ('p_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.production_plan')),
                ('w_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.workman')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('exe_type', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('info_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PtoM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.process_module')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.process_name')),
            ],
        ),
        migrations.CreateModel(
            name='Process_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=250, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('p_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.process_name')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.process_module')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.production_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('info_datetime', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=0)),
                ('userinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo')),
                ('workman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.workman')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.IntegerField(default=0)),
                ('callBoss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.callboss')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.executor')),
            ],
        ),
        migrations.CreateModel(
            name='FileModifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifyDateTime', models.DateTimeField(auto_now=True)),
                ('fileKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.filesystem')),
                ('modifyUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='executor',
            name='op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo'),
        ),
        migrations.AddField(
            model_name='executor',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.schedule'),
        ),
        migrations.AddField(
            model_name='executor',
            name='wk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.workman'),
        ),
        migrations.CreateModel(
            name='Database_manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=50, null=True)),
                ('op_datetime', models.DateTimeField(null=True)),
                ('userinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='callboss',
            name='accp_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo'),
        ),
        migrations.AddField(
            model_name='callboss',
            name='send_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.workman'),
        ),
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appendix_name', models.CharField(max_length=50, null=True)),
                ('appendix_type', models.CharField(max_length=50, null=True)),
                ('appendix_file', models.CharField(max_length=200, null=True)),
                ('appendix_content', models.CharField(max_length=200, null=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.filesystem')),
            ],
        ),
    ]
