# Generated by Django 3.1 on 2020-11-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_plan',
            name='process_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='production_plan',
            name='process_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
