# Generated by Django 3.1 on 2020-11-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201122_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanToProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('planKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.production_plan')),
                ('processKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.process_name')),
            ],
        ),
    ]
