# Generated by Django 3.1 on 2020-11-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_plantoprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production_plan',
            name='process_count',
        ),
        migrations.RemoveField(
            model_name='production_plan',
            name='process_total',
        ),
        migrations.AddField(
            model_name='plantoprocess',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
