# Generated by Django 3.1 on 2020-12-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201122_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='workman',
            name='photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='WorkmanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileUrl', models.CharField(max_length=255, null=True)),
                ('workmanKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.workman')),
            ],
        ),
    ]
