# Generated by Django 3.1 on 2020-12-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201205_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='docSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('info_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
