# Generated by Django 3.1 on 2020-12-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201212_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('state', models.IntegerField(default=1)),
                ('info_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
