# Generated by Django 3.1 on 2020-12-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_plan_module_accountbookkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendix',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='callboss',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='chat',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='database_manage',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='docsort',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='executor',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='filemodifyrecord',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='filesystem',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='modelrecord',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='note',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='notice',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='plantoprocess',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='process_img',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='process_module',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='process_name',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='production_plan',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='ptom',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='working',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='workman',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='workmanfile',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
        migrations.AddField(
            model_name='workstate',
            name='accountBookKey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.accountbook'),
        ),
    ]
