# -*- coding:utf-8 -*-

"""
Django settings for TraumWork project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mmqu&fwd(j_#8b!f5gwx3tdwulo!7c8ha+1ez*n8+=+f1&3^h='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web.middleware_put.HttpPost2HttpOtherMiddleware',  #深坑----添加中间件，让DJANGO支持PUT DELETE操作
]

ROOT_URLCONF = 'ManageSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ManageSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'managesystem',
        'USER': 'root',
        'PASSWORD': 'liubing',
        'Host': '127.0.0.1',
        'PORT':'3306',
        #'CONN_MAX_AGE': 7200,   #2小时长连接
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"),]
MEDIA_ROOT_K = os.path.join(BASE_DIR, 'static/')  #配置kindeditor编辑器根目录，将上传到以此根基础

#UPLOADS = os.path.join(BASE_DIR, 'static/uploads')  #上传到LINUX服务器上时，要启用此行，否则拼接路径出错
UPLOADS = os.path.join(BASE_DIR, 'static/uploads')  #Python3写法
UPLOADS_URL = "/static/uploads"  #服务器URL路径

#此处大坑，解决HTML 中申明H5时(<!DOCTYPE html>)，导致样式不能解析
import mimetypes
mimetypes.add_type("text/css", ".css", True)


#邮箱服务器配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.exmail.qq.com'  # 如果是 163 改成 smtp.163.com
EMAIL_PORT = 465
EMAIL_HOST_USER = 'lgy@schalod.com' # 帐号
EMAIL_HOST_PASSWORD = '^c4mp$ox4ipyc$w4'  # 密码
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

#全局变量，获取表格查询，和排行榜查询时延时，用于前台展示加载动画
SLEEP_TIME_TABLE = 0.01
SLEEP_TIME_RANK = 0.01
